//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nlayer.Samples.NLayerApp.Domain.Main.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nlayer.Samples.NLayerApp.Domain.Main.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot deposit money in locked account.
        /// </summary>
        internal static string exception_BankAccountCannotDeposit {
            get {
                return ResourceManager.GetString("exception_BankAccountCannotDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot withdraw in bankaccount, this is locked or amount is greather than balance.
        /// </summary>
        internal static string exception_BankAccountCannotWithdraw {
            get {
                return ResourceManager.GetString("exception_BankAccountCannotWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid amount for withdraw operation.
        /// </summary>
        internal static string exception_BankAccountInvalidWithdrawAmount {
            get {
                return ResourceManager.GetString("exception_BankAccountInvalidWithdrawAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country is null or Country is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullCountry {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer is null or Customer is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullCustomer {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product is null or Product is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullProduct {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot transfer money to the same bank account.
        /// </summary>
        internal static string exception_CannotTransferMoneyWhenFromIsTheSameAsTo {
            get {
                return ResourceManager.GetString("exception_CannotTransferMoneyWhenFromIsTheSameAsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid data in order line, check the values, amount of items must be greater than zero.
        /// </summary>
        internal static string exception_InvalidDataForOrderLine {
            get {
                return ResourceManager.GetString("exception_InvalidDataForOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid order number pattern .
        /// </summary>
        internal static string exception_OrderNumberSpecificationInvalidOrderNumberPattern {
            get {
                return ResourceManager.GetString("exception_OrderNumberSpecificationInvalidOrderNumberPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposit from account with identifier {0}.
        /// </summary>
        internal static string messages_TransactionFromMessage {
            get {
                return ResourceManager.GetString("messages_TransactionFromMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Withdraw to account with identifier {0}.
        /// </summary>
        internal static string messages_TransactionToMessage {
            get {
                return ResourceManager.GetString("messages_TransactionToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The bank account number cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankAccountNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankAccountNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The bank account check digits cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankCheckDigitsCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankCheckDigitsCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The bank account national bank code cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankNationalBankCodeCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankNationalBankCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The bank account office number cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankOfficeNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankOfficeNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The customer id  in bank account cannot be empty.
        /// </summary>
        internal static string validation_BankAccountCustomerIdIsEmpty {
            get {
                return ResourceManager.GetString("validation_BankAccountCustomerIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The bank account number cannot be null.
        /// </summary>
        internal static string validation_BankAccountNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CountryISOCode cannot be null or empty string.
        /// </summary>
        internal static string validation_CountryCountryISOCodeCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CountryCountryISOCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CountryName cannot be null or empty string.
        /// </summary>
        internal static string validation_CountryCountryNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CountryCountryNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CountryId is not associated for this Customer.
        /// </summary>
        internal static string validation_CustomerCountryIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_CustomerCountryIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The FirstName property cannot be null or empty string.
        /// </summary>
        internal static string validation_CustomerFirstNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CustomerFirstNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The LastName property cannot be null or empty string.
        /// </summary>
        internal static string validation_CustomerLastNameCannotBeBull {
            get {
                return ResourceManager.GetString("validation_CustomerLastNameCannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer is null or Customer is in Transient state.
        /// </summary>
        internal static string validation_OrderCustomerIdCannotBenull {
            get {
                return ResourceManager.GetString("validation_OrderCustomerIdCannotBenull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Amount property cannot be less than 1.
        /// </summary>
        internal static string validation_OrderLineAmountLessThanOne {
            get {
                return ResourceManager.GetString("validation_OrderLineAmountLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Discount cannot be less than 0 or greater than 1.
        /// </summary>
        internal static string validation_OrderLineDiscountCannotBeLessThanZeroOrGreaterThanOne {
            get {
                return ResourceManager.GetString("validation_OrderLineDiscountCannotBeLessThanZeroOrGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OrderLine cannot have associated order.
        /// </summary>
        internal static string validation_OrderLineOrderIdIsEmpty {
            get {
                return ResourceManager.GetString("validation_OrderLineOrderIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product id cannot be a empty identifier.
        /// </summary>
        internal static string validation_OrderLineProductIdCannotBeNull {
            get {
                return ResourceManager.GetString("validation_OrderLineProductIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UnitPrice cannot be less than zero.
        /// </summary>
        internal static string validation_OrderLineUnitPriceLessThanZero {
            get {
                return ResourceManager.GetString("validation_OrderLineUnitPriceLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount in stock cannot be less than zero.
        /// </summary>
        internal static string validation_ProductAmountLessThanZero {
            get {
                return ResourceManager.GetString("validation_ProductAmountLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description cannot be null or empty.
        /// </summary>
        internal static string validation_ProductDescriptionCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("validation_ProductDescriptionCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title cannot be null or empty.
        /// </summary>
        internal static string validation_ProductTitleCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("validation_ProductTitleCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UnitPrice in stock cannot be less than zero.
        /// </summary>
        internal static string validation_ProductUnitPriceLessThanZero {
            get {
                return ResourceManager.GetString("validation_ProductUnitPriceLessThanZero", resourceCulture);
            }
        }
    }
}
