//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Main.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Main.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot perform the transfer, invalid data in accounts specifications.
        /// </summary>
        internal static string error_CannotPerformTransferInvalidAccounts {
            get {
                return ResourceManager.GetString("error_CannotPerformTransferInvalidAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The country id is empty, you cannot add a new customer without country reference.
        /// </summary>
        internal static string exception_InvalidCountryIdentifier {
            get {
                return ResourceManager.GetString("exception_InvalidCountryIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The customer identifier is empty.
        /// </summary>
        internal static string exception_InvalidCustomerIdentifier {
            get {
                return ResourceManager.GetString("exception_InvalidCustomerIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid page index or page count data.
        /// </summary>
        internal static string exception_InvalidPageIndexOrPageCount {
            get {
                return ResourceManager.GetString("exception_InvalidPageIndexOrPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order total is greater customer credit, you cannot perform new order.
        /// </summary>
        internal static string info_OrderTotalIsGreaterCustomerCredit {
            get {
                return ResourceManager.GetString("info_OrderTotalIsGreaterCustomerCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot add a new book with a null book dto.
        /// </summary>
        internal static string warning_CannotAddBookWithNullInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddBookWithNullInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot add customer. The dto is null or the country identifier is empty.
        /// </summary>
        internal static string warning_CannotAddCustomerWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddCustomerWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot add not validated bank account.
        /// </summary>
        internal static string warning_CannotAddNotValidatedBankAccount {
            get {
                return ResourceManager.GetString("warning_CannotAddNotValidatedBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot add null bank account or bank account without customer identifier.
        /// </summary>
        internal static string warning_CannotAddNullBankAccountOrInvalidCustomer {
            get {
                return ResourceManager.GetString("warning_CannotAddNullBankAccountOrInvalidCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot add a new order with a null order dto.
        /// </summary>
        internal static string warning_CannotAddOrderWithNullInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddOrderWithNullInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot add a new software with a null order dto.
        /// </summary>
        internal static string warning_CannotAddSoftwareWithNullInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddSoftwareWithNullInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot create bank account for not existing customer.
        /// </summary>
        internal static string warning_CannotCreateBankAccountForInvalidCustomer {
            get {
                return ResourceManager.GetString("warning_CannotCreateBankAccountForInvalidCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot create a bank account for non existing customer.
        /// </summary>
        internal static string warning_CannotCreateBankAccountForNonExistingCustomer {
            get {
                return ResourceManager.GetString("warning_CannotCreateBankAccountForNonExistingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot create a new order for non existing customer.
        /// </summary>
        internal static string warning_CannotCreateOrderForNonExistingCustomer {
            get {
                return ResourceManager.GetString("warning_CannotCreateOrderForNonExistingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot get bank account activity for invalid or not existing account.
        /// </summary>
        internal static string warning_CannotGetActivitiesForInvalidOrNotExistingBankAccount {
            get {
                return ResourceManager.GetString("warning_CannotGetActivitiesForInvalidOrNotExistingBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot get orders from empty customer id.
        /// </summary>
        internal static string warning_CannotGetOrdersFromEmptyCustomerId {
            get {
                return ResourceManager.GetString("warning_CannotGetOrdersFromEmptyCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot lock bank account ,the identifier is empty.
        /// </summary>
        internal static string warning_CannotLockBankAccountWithEmptyIdentifier {
            get {
                return ResourceManager.GetString("warning_CannotLockBankAccountWithEmptyIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot lock non existing bank account, the unknown key is {0}.
        /// </summary>
        internal static string warning_CannotLockNonExistingBankAccount {
            get {
                return ResourceManager.GetString("warning_CannotLockNonExistingBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot remove customer with empty id.
        /// </summary>
        internal static string warning_CannotRemoveCustomerWithEmptyId {
            get {
                return ResourceManager.GetString("warning_CannotRemoveCustomerWithEmptyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot remove a non existing customer.
        /// </summary>
        internal static string warning_CannotRemoveNonExistingCustomer {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot add customer. The dto is null or the identifier is empty.
        /// </summary>
        internal static string warning_CannotUpdateCustomerWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotUpdateCustomerWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot update a non existing customer.
        /// </summary>
        internal static string warning_CannotUpdateNonExistingCustomer {
            get {
                return ResourceManager.GetString("warning_CannotUpdateNonExistingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid argument for FindCustomer, the customerid cannot be empty.
        /// </summary>
        internal static string warning_InvalidArgumentForFindCustomer {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentForFindCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid arguments when call to CustomerManagementService FindOrders.
        /// </summary>
        internal static string warning_InvalidArgumentForFindOrders {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentForFindOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid arguments when call to CustomerManagementService FindProducts.
        /// </summary>
        internal static string warning_InvalidArgumentForFindProducts {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentForFindProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid arguments when call to CustomerManagementService FindCountries.
        /// </summary>
        internal static string warning_InvalidArgumentsForFindCountries {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentsForFindCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid arguments when call to CustomerManagementService FindCustomers.
        /// </summary>
        internal static string warning_InvalidArgumentsForFindCustomers {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentsForFindCustomers", resourceCulture);
            }
        }
    }
}
